# Generated by Django 3.2.14 on 2023-10-31 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onroadservice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
            ],
        ),
    ]
