# Generated by Django 3.2.14 on 2023-10-31 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onroadservice', '0005_own_service_request'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='request',
            new_name='request_service',
        ),
    ]
