# Generated by Django 3.2.14 on 2023-10-31 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onroadservice', '0006_rename_request_request_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='own_service',
            name='Amount',
        ),
    ]
