# Generated by Django 3.2.14 on 2023-10-31 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onroadservice', '0007_remove_own_service_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_service',
            name='longitude',
            field=models.CharField(default=1, max_length=200),
        ),
    ]
