# Generated by Django 3.2.14 on 2023-10-31 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onroadservice', '0009_rating_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating_reviews',
            name='Worker',
        ),
        migrations.AddField(
            model_name='rating_reviews',
            name='WORKER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='onroadservice.worker'),
        ),
        migrations.AddField(
            model_name='user',
            name='LOGIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='onroadservice.login'),
        ),
        migrations.AddField(
            model_name='worker',
            name='LOGIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='onroadservice.login'),
        ),
        migrations.AlterField(
            model_name='own_service',
            name='SERVICE',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='onroadservice.service'),
        ),
        migrations.AlterField(
            model_name='own_service',
            name='WORKER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='onroadservice.worker'),
        ),
        migrations.AlterField(
            model_name='request_service',
            name='OWN_SERVICE',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='onroadservice.own_service'),
        ),
        migrations.AlterField(
            model_name='request_service',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='onroadservice.user'),
        ),
    ]
