# Generated by Django 3.2.14 on 2023-10-31 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onroadservice', '0010_auto_20231031_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating_reviews',
            name='customer',
        ),
        migrations.AddField(
            model_name='rating_reviews',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='onroadservice.user'),
        ),
    ]
